//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServisOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTEKNIKSERVISEntities : DbContext
    {
        public DBTEKNIKSERVISEntities()
            : base("name=DBTEKNIKSERVISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Araclar> TBL_Araclar { get; set; }
        public virtual DbSet<TBL_ArızaDetay> TBL_ArızaDetay { get; set; }
        public virtual DbSet<TBL_Cari> TBL_Cari { get; set; }
        public virtual DbSet<TBL_Departman> TBL_Departman { get; set; }
        public virtual DbSet<TBL_FaturaBilgi> TBL_FaturaBilgi { get; set; }
        public virtual DbSet<TBL_FaturaDetay> TBL_FaturaDetay { get; set; }
        public virtual DbSet<TBL_Gider> TBL_Gider { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Notlarım> TBL_Notlarım { get; set; }
        public virtual DbSet<TBL_Personel> TBL_Personel { get; set; }
        public virtual DbSet<TBL_Urun> TBL_Urun { get; set; }
        public virtual DbSet<TBL_UrunHareket> TBL_UrunHareket { get; set; }
        public virtual DbSet<TBL_UrunKabul> TBL_UrunKabul { get; set; }
        public virtual DbSet<TBL_UrunTakip> TBL_UrunTakip { get; set; }
    }
}
