//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UrunKabul
    {
        public int ISLEMID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> CARI { get; set; }
        public Nullable<short> PERSONEL { get; set; }
        public Nullable<System.DateTime> GELISTARIHI { get; set; }
        public Nullable<System.DateTime> CIKISTARİHİ { get; set; }
    
        public virtual TBL_Cari TBL_Cari { get; set; }
        public virtual TBL_Personel TBL_Personel { get; set; }
        public virtual TBL_Urun TBL_Urun { get; set; }
    }
}
